# AUTO-GENERATED by /generate-gdt — do not edit manually.
# This file is replaced entirely each time the skill runs for a new part.
"""Add manufacturing dimensions and tolerances to TechDraw views.

Matches edges by curve type + length to sim/constants.py values,
then places DrawViewDimension objects. Tolerance config from layout_spec.yaml.
"""

from pathlib import Path

import yaml

LAYOUT_SPEC_PATH = Path("cad/layout_spec.yaml")

# Reason: tolerances for matching edges to known constants.
# Edges won't be exactly the constant value due to HLR + floating point.
EDGE_MATCH_TOL = 0.5  # mm


def _load_tolerances() -> dict:
    spec = yaml.safe_load(LAYOUT_SPEC_PATH.read_text())
    return spec.get("tolerances", {})


def _find_edge_by_length(
    view, target_length: float, curve_type: str = "Line"
) -> str | None:
    """Match a visible edge by curve type and length within tolerance.

    Returns edge reference string like "Edge5" or None if no match.
    """
    edges = view.getVisibleEdges()
    for i, edge in enumerate(edges):
        ctype = type(edge.Curve).__name__
        if ctype != curve_type:
            continue
        if abs(edge.Length - target_length) < EDGE_MATCH_TOL:
            return f"Edge{i}"
    return None


def _find_circle_by_radius(view, target_radius: float) -> str | None:
    """Match a visible circle/arc edge by radius."""
    edges = view.getVisibleEdges()
    for i, edge in enumerate(edges):
        ctype = type(edge.Curve).__name__
        if ctype not in ("Circle", "BSplineCurve"):
            continue
        if (
            hasattr(edge.Curve, "Radius")
            and abs(edge.Curve.Radius - target_radius) < EDGE_MATCH_TOL
        ):
            return f"Edge{i}"
    return None


def _find_all_circles_by_radius(view, target_radius: float) -> list[str]:
    """Find all circle edges matching a radius (holes split into half-arcs)."""
    edges = view.getVisibleEdges()
    matches = []
    for i, edge in enumerate(edges):
        ctype = type(edge.Curve).__name__
        if ctype not in ("Circle", "BSplineCurve"):
            continue
        if (
            hasattr(edge.Curve, "Radius")
            and abs(edge.Curve.Radius - target_radius) < EDGE_MATCH_TOL
        ):
            matches.append(f"Edge{i}")
    return matches


def add_dimensions(doc, page, views: dict) -> list[str]:
    """Add manufacturing dimensions to TechDraw views.

    Args:
        doc: FreeCAD document
        page: TechDraw page object
        views: dict mapping view name to DrawViewPart object
            e.g. {"FRONT": front_view, "RIGHT": right_view, ...}

    Returns:
        List of dimension names added (for logging).
    """
    tols = _load_tolerances()
    hole_tols = tols.get("holes", {})
    added = []

    # --- Front view dimensions ---
    front = views.get("FRONT")
    if front:
        added += _dim_front(doc, page, front)

    # --- Right view dimensions ---
    right = views.get("RIGHT")
    if right:
        added += _dim_right(doc, page, right, hole_tols)

    doc.recompute()
    return added


def _add_dim(doc, page, name, dim_type, view, edge, fmt, x=None, y=None):
    """Create a dimension, add to page, then set position.

    Reason: addView resets X/Y to defaults. Must set position after.
    """
    dim = doc.addObject("TechDraw::DrawViewDimension", name)
    dim.Type = dim_type
    dim.References2D = [(view, edge)]
    dim.FormatSpec = fmt
    page.addView(dim)
    if x is not None:
        dim.X = x
    if y is not None:
        dim.Y = y
    return dim


def _dim_front(doc, page, view) -> list[str]:
    """Add dimensions to front view: height, width, thickness, fillet."""
    added = []
    # Reason: getVisibleEdges() returns model-space lengths, not scaled.

    # Vertical leg height (80mm) — left side, offset left of view
    edge = _find_edge_by_length(view, 80.0)
    if edge:
        _add_dim(doc, page, "DimHeight", "DistanceY", view, edge, "%.0f", x=-50, y=0)
        added.append("DimHeight")

    # Total width (74mm) — bottom, offset below view
    edge = _find_edge_by_length(view, 74.0)
    if edge:
        _add_dim(doc, page, "DimWidth", "DistanceX", view, edge, "%.0f", x=0, y=-50)
        added.append("DimWidth")

    # Bracket thickness (14mm) — right side
    # Reason: the 14mm edge is vertical, so DistanceX gives 0. Use "Distance" instead.
    edge = _find_edge_by_length(view, 14.0)
    if edge:
        _add_dim(doc, page, "DimThickness", "Distance", view, edge, "%.0f", x=25, y=-15)
        added.append("DimThickness")

    # Fillet radius (R8) — near the fillet, offset up-right
    edge = _find_circle_by_radius(view, 8.0)
    if edge:
        _add_dim(doc, page, "DimFillet", "Radius", view, edge, "R%.0f", x=-15, y=15)
        added.append("DimFillet")

    return added


def _dim_right(doc, page, view, hole_tols: dict) -> list[str]:
    """Add dimensions to right view: hole diameter, bolt spacing, width."""
    added = []

    # Bolt hole diameter (⌀8.5 H9) — use longest arc for cleanest dim line
    hole_edges = _find_all_circles_by_radius(view, 4.25)
    if hole_edges:
        # Reason: pick the longest arc — gives the cleanest diameter dimension.
        # Short arc fragments produce awkward leader lines.
        edges = view.getVisibleEdges()
        longest = max(hole_edges, key=lambda e: edges[int(e[4:])].Length)
        fit_class = hole_tols.get("fit_class", "H9")
        dim = _add_dim(
            doc,
            page,
            "DimHoleDia",
            "Diameter",
            view,
            longest,
            f"2X ⌀%.1f {fit_class}",
            x=35,
            y=20,
        )
        dim.EqualTolerance = False
        dim.FormatSpecOverTolerance = "%+.3w"
        dim.FormatSpecUnderTolerance = "%+.3w"
        dim.OverTolerance = hole_tols.get("over_tolerance", 0.036)
        dim.UnderTolerance = hole_tols.get("under_tolerance", 0.0)
        added.append("DimHoleDia")

    # Bracket width (50mm) — below view
    edge = _find_edge_by_length(view, 50.0)
    if edge:
        _add_dim(
            doc, page, "DimBracketWidth", "DistanceX", view, edge, "%.0f", x=0, y=-40
        )
        added.append("DimBracketWidth")

    return added


def add_view_labels(doc, page, positions: dict[str, tuple[float, float]]) -> list[str]:
    """Add view labels via DrawViewAnnotation.

    IMPORTANT: X/Y must be set AFTER page.addView(), then doc.recompute().
    Setting before addView gets overwritten to page center.
    """
    added = []
    for name, (x, y) in positions.items():
        anno = doc.addObject("TechDraw::DrawViewAnnotation", f"Label{name}")
        anno.Text = [name]
        anno.TextSize = 5.0
        page.addView(anno)
        # Reason: addView resets X/Y to page center. Must set after.
        anno.X = x
        anno.Y = y
        added.append(f"Label{name}")

    doc.recompute()
    return added
